### ISSUE TITLE
Unable to install COMETSC

### ISSUE THREAD

**Issue by mdidish** [MSingerLab/COMETSC#13]
Dear,
I failed to install locally COMETSC, on Ubuntu 20.04 with Python 3.6.8:
`pip3 install COMETSC`
give this error :
```
ERROR: Cannot install cometsc==0.1.10, cometsc==0.1.11, cometsc==0.1.12, cometsc==0.1.13, cometsc==0.1.5, cometsc==0.1.6, cometsc==0.1.7 and cometsc==0.1.9 because these package versions have conflicting dependencies.

The conflict is caused by:
    cometsc 0.1.13 depends on scikit-learn==0.21.0
    cometsc 0.1.12 depends on scikit-learn==0.21.0
    cometsc 0.1.11 depends on scikit-learn==0.21.0
    cometsc 0.1.10 depends on scikit-learn==0.21.0
    cometsc 0.1.9 depends on scikit-learn==0.21.0
    cometsc 0.1.7 depends on scikit-learn==0.21.0
    cometsc 0.1.6 depends on scikit-learn==0.21.0
    cometsc 0.1.5 depends on scikit-learn==0.21.0
```

On scikit-learn github, we can read this:
"Also we removed the 0.21.0 tarball from pypi because it lacked a metadata that made it explicit that it was not compatible with python 2."

So how do you recommend installing COMETSC?

Best,
Marc

**Comment by XinLi-0419** [comment]
@mdidish 

Hi, do you happen to have a solution for this now? I am running into the same error. Thanks!

**Comment by mdidish** [comment]
No I didn't, I still use the web version. Tell me if you find one!
Best

⁣Télécharger TypeApp pour Android ​

Le 2 nov. 2021 à 20:38, à 20:38, Shinlee419 ***@***.***> a écrit:
***@***.***

**Comment by XinLi-0419** [comment]
> No I didn't, I still use the web version. Tell me if you find one! Best ⁣Télécharger TypeApp pour Android ​ Le 2 nov. 2021 à 20:38, à 20:38, Shinlee419 ***@***.***> a écrit: ***@***.***
> […](#)

Sure thing.

Sadly, the web version is not working for me. I am okay with downsampling but it is saying Internal Server Error after I submit.

**Comment by mdidish** [comment]
Concerning the web version, cluster's names have to be number. The contact indicated on their website answered to my questions and helped me.

⁣Télécharger TypeApp pour Android ​

Le 2 nov. 2021 à 22:08, à 22:08, Shinlee419 ***@***.***> a écrit:

**Comment by oshahid** [comment]
Hi all,

I was able to fix the Internal Server Error on the COMET website. I'll leave this thread open if you'd like to diagnose any problems you may still have with local installation of COMET on your computer.

**Comment by desmondramirez** [comment]
Hi,

I have the same issue trying to install comet on my cluster. Is it possible to change the requirements for a version of scikit-learn that hasn't been replaced with a different name by the developer? I happen to have scikit-learn 0.21 installed on my home computer, but looks like it would take over 3 days running on my laptop-- not ideal. I am running on the web server, but would like to be able to run them independently.

Thanks for the program though, it's very useful!

**Comment by oshahid** [comment]
Hi desmondramirez,

Can you tell me which version of Python you are using? I've noticed that even with some version of Python 3.6 (like 3.6.8, for example), scikit-learn gives a few issues. Using Python 3.6.0 or 3.6.2 should resolve the issue. Otherwise, a temporary work-around that I've tried is the following, which works if you have conda or anaconda installed already:

1.) Create a temporary environment using Anaconda called "COMET" which uses Python 3.6:

conda create -n COMET python=3.6.2

2.) Activate the environment

conda activate COMET

3.) Now your computer should see you using Python 3.6 in the COMET environment. To check, do the following:

python -V

4.) You should end up with Python 3.6.2. Now use this version of Python to install your COMET virtual environment::

pip install COMETSC

In the meantime, I will try changing the requirements for scikit-learn so that a more current version will be available. Please let me know if this solution works for you, or if you still run into issues.

**Comment by mdidish** [comment]
@oshahid Perfect, it works for me!
Best,
