### ISSUE TITLE
Web version - 3 and 4 marker panels

### ISSUE THREAD

**Issue by CodeInTheSkies** [MSingerLab/COMETSC#4]
Hello,
For the web version, is there an option to obtain more than "pairs" of markers?  That is, the 3 and 4-marker panels?
I know this is possible in the installed version, but I would like to use this on the web version, if possible.
Thanks!

**Comment by Cnrdelaney** [comment]
Hello,

At the moment, this is not possible on the web version due to the size of the instance we are using for computing and runtime considerations, there are potentially plans to add this in the future but for now this is only available on the installed version. 

If you would like help installing on your local, we have good documentation available (https://hgmd.readthedocs.io/en/latest/quickstart.html) and I would be more than happy to walk you through it over email as well (cdelaney@ds.dfci.harvard.edu) :)
